#!/bin/bash
set -e

if [ $# -lt 1 ]; then
    echo "./gen_sdk_sample.sh [chm|pdf]"
    exit
fi

if [ $1 == "chm" ]; then
    echo $1
elif [ $1 == "pdf" ]; then
    echo $1
else
    echo "params is error!!!"
    exit
fi

#remove files
if [ ! -d  "gy_sample/html/" ]; then
    mkdir gy_sample/html
fi

rm -rf gy_sample/html/*

#cp gy_sample/src/kgxx_log.png gy_sample/html

cd gy_sample
../tools/doxygen.exe SDKDEMODOX

if [ $1 == "chm" ]; then
    ../tools/hhc.exe ./html/index.hhp
elif [ $1 == "pdf" ]; then
    sed -i 's/\\begin{document}/\\usepackage{CJKutf8}\n\\begin{document}\n\\begin{CJK}{UTF8}{gbsn}/g' latex/refman.tex
    sed -i 's/\\end{document}/\\end{CJK}\n\\end{document}/g' latex/refman.tex
    sed -i 's/Generated by Doxygen 1.9.7/Generated by kgmicro 1.0.0/g' latex/refman.tex
    sed -i 's/Generated by Doxygen/Generated by kgmicro/g' latex/refman.tex

    cd latex
    cmd.exe /c make.bat

    mv refman.pdf ../../sdk_sample.pdf
fi